apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: person-deployment
  name: person-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: person-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: person-deployment
    spec:
      containers:
      - image: docker.io/ashwanisolanki/person:v1
        name: person
        ports:
        - containerPort: 8080
