apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app : customer-deployment-labelValue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-deployment-labelValue
  template:
    metadata:
      labels:
        app : customer-deployment-labelValue
    spec:
      containers:
      - image: docker.io/ashwanisolanki/customer:v1
        name: customer
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    serviceType: customer-nodePort
spec:
  selector:
    app: customer-deployment-labelValue
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8080