apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-deployment
  labels:
    app: person-deployment-label-value
spec:
  replicas: 2
  selector:
    matchLabels:
      app: person-deployment-label-value
  template:
    metadata:
      labels:
        app: person-deployment-label-value
    spec:
      containers:
      - image: docker.io/ashwanisolanki/person:v1
        name: person
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: person-service
  labels:
    servicetype: person-nodeport
spec:
  selector:
    app: person-deployment-label-value
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8080